export const jobs = [
    {
        id: '1',
        role: 'Product Manager',
        company: 'Internshala',
        location: 'Gurugram, Haryana',
        salary: '₹ 25,0000/month',
        period: '6 months',
        postedOn: 'Posted 2 days ago',
        companyIcon: 'is',
        rating: [true, true, true, true, true],
        selected: false,
        aboutCompany: 'Google, LLC is an American multinational technology company that specializes in Internet-related services and products, which include online advertising technologies, a search engine, cloud computing, software, and hardware. It is considered one of the Big Five technology companies in the U.S. information technology industry, alongside Amazon, Facebook, Apple, and Microsoft.',
        aboutInternship: [
            '• As a User Interface Designer, you will be required to work closely with Product Managers, Developers, Consultants & other key stakeh olders.',
            '• Your primary task as hand would be to design mockups & create prototypes basis the signed-off wireframes & userflows.',
        ],
        skills: ['Adobe photoshop', 'Adobe illustrator', 'HTML', 'Adobe After Effects', 'Figma'],
        whoCanApply: ["Only those candidates can apply who:",
            "1. are available for the work from home job/internship",
            "2. can start the work from home job/internship between 4th Nov'20 and 9th Dec'20",
            "3. are available for duration of 3 months",
            "4. have relevant skills and interests"]
    },
    {
        id: '2',
        role: 'Graphic Designer',
        company: 'Google',
        location: 'Gurugram, Haryana',
        salary: '₹ 25,0000/month',
        period: '6 months',
        postedOn: 'Posted 2 days ago',
        companyIcon: 'google',
        rating: [true, true, true, true, true],
        selected: false,
        aboutCompany: 'Google, LLC is an American multinational technology company that specializes in Internet-related services and products, which include online advertising technologies, a search engine, cloud computing, software, and hardware. It is considered one of the Big Five technology companies in the U.S. information technology industry, alongside Amazon, Facebook, Apple, and Microsoft.',
        aboutInternship: [
            '• As a User Interface Designer, you will be required to work closely with Product Managers, Developers, Consultants & other key stakeh olders.',
            '• Your primary task as hand would be to design mockups & create prototypes basis the signed-off wireframes & userflows.',
        ],
        skills: ['Adobe photoshop', 'Adobe illustrator', 'HTML', 'Adobe After Effects', 'Figma'],
        whoCanApply: ["Only those candidates can apply who:",
            "1. are available for the work from home job/internship",
            "2. can start the work from home job/internship between 4th Nov'20 and 9th Dec'20",
            "3. are available for duration of 3 months",
            "4. have relevant skills and interests"]
    },
    {
        id: '3',
        role: 'UI Designer',
        company: 'Lollypop Designs Private Ltd',
        location: 'Hauz khas, New delhi',
        salary: '₹ 25,0000/month',
        period: '6 months',
        postedOn: 'Posted 15 days ago',
        companyIcon: 'ls',
        rating: [true, true, true, true, false],
        selected: false,
        aboutCompany: 'Google, LLC is an American multinational technology company that specializes in Internet-related services and products, which include online advertising technologies, a search engine, cloud computing, software, and hardware. It is considered one of the Big Five technology companies in the U.S. information technology industry, alongside Amazon, Facebook, Apple, and Microsoft.',
        aboutInternship: [
            '• As a User Interface Designer, you will be required to work closely with Product Managers, Developers, Consultants & other key stakeh olders.',
            '• Your primary task as hand would be to design mockups & create prototypes basis the signed-off wireframes & userflows.',
        ],
        skills: ['Adobe photoshop', 'Adobe illustrator', 'HTML', 'Adobe After Effects', 'Figma'],
        whoCanApply: ["Only those candidates can apply who:",
            "1. are available for the work from home job/internship",
            "2. can start the work from home job/internship between 4th Nov'20 and 9th Dec'20",
            "3. are available for duration of 3 months",
            "4. have relevant skills and interests"]
    },
    {
        id: '4',
        role: 'Visual Designer',
        company: 'Alcon',
        location: 'Hauz khas, New delhi',
        salary: '₹ 25,0000/month',
        period: '6 months',
        postedOn: 'Posted 15 days ago',
        companyIcon: 'alcon',
        rating: [true, true, false, false, false],
        selected: false,
        aboutCompany: 'Google, LLC is an American multinational technology company that specializes in Internet-related services and products, which include online advertising technologies, a search engine, cloud computing, software, and hardware. It is considered one of the Big Five technology companies in the U.S. information technology industry, alongside Amazon, Facebook, Apple, and Microsoft.',
        aboutInternship: [
            '• As a User Interface Designer, you will be required to work closely with Product Managers, Developers, Consultants & other key stakeh olders.',
            '• Your primary task as hand would be to design mockups & create prototypes basis the signed-off wireframes & userflows.',
        ],
        skills: ['Adobe photoshop', 'Adobe illustrator', 'HTML', 'Adobe After Effects', 'Figma'],
        whoCanApply: ["Only those candidates can apply who:",
            "1. are available for the work from home job/internship",
            "2. can start the work from home job/internship between 4th Nov'20 and 9th Dec'20",
            "3. are available for duration of 3 months",
            "4. have relevant skills and interests"]
    },
];